#%Module1.0

set compilernames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLCOMPILER" ""]]

module-whatis "atlas"
module-whatis "Version: VERSION"
module-whatis "Compiler: $compilernames"

# Figure out the applicable compiler--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Report an error if neither applies.
if [info exists env(ATLASHOME)] {
  foreach {compiler} $compilernames {
    if {[string first "/$compiler" $::env(ATLASHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $compilernames]} {
      set compiler $module
    }
  }
}
if { ! [info exists compiler] } {
  puts stderr "Need to load a compiler module first"
  exit 1
}

setenv ATLASHOME /opt/atlas/$compiler
prepend-path LD_LIBRARY_PATH /opt/atlas/$compiler/lib
prepend-path LIBPATH /opt/atlas/$compiler/lib
