NAME    = atlas_$(ROLLCOMPILER)
VERSION = 3.10.0
RELEASE = 0

SRC_SUBDIR	= atlas

ATLAS_NAME	= atlas
ATLAS_VERSION	= $(VERSION)
ATLAS_SOURCE	= $(ATLAS_NAME)-$(ATLAS_VERSION).tar.gz

LAPACK_NAME	= lapack
LAPACK_VERSION	= 3.4.2
LAPACK_SOURCE	= $(LAPACK_NAME)-$(LAPACK_VERSION).tgz

TAR_GZ_PKGS	= $(ATLAS_SOURCE)
TGZ_PKGS	= $(LAPACK_SOURCE)
RPM.EXTRAS         = AutoReq:No
